--  앞에 주석 처리 하면서 하다가 모르고 닫기 눌러서 날라갔어요................

-- SELECT * FROM products WHERE buyPrice BETWEEN 50 and 100;
-- UPDATE customers SET addressLine1 = 111 WHERE customerNumber = 1;
-- UPDATE products SET buyPrice = 5555 WHERE productCode = 1;
-- UPDATE employees SET jobTitle = 'aaa' WHERE employeeNumber = 1;
-- UPDATE offices SET phone= '100-292-3933' WHERE officeCode = 1;
-- UPDATE orders SET status= 'zzz WHERE orderNumber = 1;
-- UPDATE productlines SET textDescription= 'dddd' WHERE productLine = 1;
-- UPDATE products SET buyPrice= buyPrice * 1.05;
-- DELETE FROM customers WHERE customerNumber = 1;
-- DELETE FROM products WHERE productCode = 1;
-- DELETE FROM employees WHERE employeeNumber = 1;
-- DELETE FROM offices WHERE officeCode = 1;
-- DELETE FROM orders WHERE orderNumber = 1;
-- DELETE FROM orderdetails WHERE orderNumber = 1;
-- DELETE FROM payments WHERE customerNumber =1;
-- DELETE FROM productlines WHERE productLine = 1;
-- DELETE FROM customers WHERE customerNumber = 1;
-- DELETE FROM products WHERE productCode = 1;
